apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: diario
  labels:
    app: api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: diario-api
  namespace: diario
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: diario-worker
  namespace: diario
